services:
  - type: web
    name: petshop-prado
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: petshop-prado-minha-senha-secreta-2024
    disks:
      - name: petshop-data
        mountPath: /opt/render/project/src/data
        sizeGB: 1
